site_name: Platform Optimization SDK for Citrix Receiver for Linux 13.10
site_description: Reference guide for Platform Optimization SDK for Citrix Receiver for Linux 13.10
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
     anchorlink: true

pages:
  - Home: index.md
